### ISSUE TITLE
Api.Ai.ApplicationService.dll could not be found

### ISSUE THREAD

**Issue by cachebust** [brunobrandes/api-ai-csharp#3]
Hey,

I'm facing this error when tried running Api.Ai.Example.Console
It says : 

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file '..\..\..\src\ApplicationService\Api.Ai.ApplicationService\bin\Release\Api.Ai.ApplicationService.dll' could not be found	Api.Ai.Example.Console	C:\Projects\api-ai-csharp-master\example\Console\Api.Ai.Example.Console\CSC	1	Active

Let me know what I'm missing here.
PS, I'm using .NET Framework 4.6.1

**Comment by brunobrandes** [comment]
Hello @Dexu5 
I remove incorrect Api.Ai.ApplicationService.dll in analyzer reference 😀
Get last commit (pull).
Example project it's working 😉
