### ISSUE TITLE
The Query does not return parameters

### ISSUE THREAD

**Issue by vhugogarcia** [brunobrandes/api-ai-csharp#4]
How can you make the query to return the parameters from Api.AI?

Thanks in advance

**Comment by brunobrandes** [comment]
After making a call to api.ai, you receive the **QueryResponse** object

Ex:

``` csharp
var queryRequest = new QueryRequest
{
SessionId = "1",
Query = new string [] {"My email is test@gmail.com"},
Lang = Domain.Enum.Language.English
};

var queryResponse = await queryAppService.PostQueryAsync(queryRequest);
```

If on return intent, there are parameters the same are in **queryResponse.Result.Parameters**
You can fetch the values through an extension by passing the parameter key.

Ex:

``` csharp
var email = queryResponse.Result.GetParameterValueByKey("email").ToString();
```
Is that your need?

**Comment by vhugogarcia** [comment]
That is what I was looking for yeah. 

Thanks @brunobrandes 

Excuse me, I would like to ask you 2 quick questions before close this ticket:
- The session Id should be a random number or random GUID or what is expected to be?
- I saw in the roadmap there is Intents management so we can add new intents a long with utterances and answers, Is there a way to take a look at that progress?

Thanks in advance for the amazing wrapper library.

**Comment by brunobrandes** [comment]
* **"The session Id should be a random number or random GUID or what is expected to be?"**
SessionId is a string token up to 36 symbols long, used to identify the client and to manage session parameters (including contexts) per client. 
Use the same GUID per user/session.

* **"I saw in the roadmap there is Intents management so we can add new intents a long with utterances and answers, Is there a way to take a look at that progress?"**
I have not yet implemented intent management. Feel free to submit a pull request with this implemented feature 😀

* **"Thanks in advance for the amazing wrapper library."**
Thank you very much! 

hugs
